print("a,b,,c".rsplit(","))
print("a,b,,c".rsplit(",", 2))
print("a--b--".rsplit("--"))
print("abc".rsplit("z"))
print("".rsplit(","), "".rsplit())
print("  alpha  beta  gamma  ".rsplit())
print("  alpha  beta  gamma  ".rsplit(None, 1))
print("a b c".rsplit(None, True))
print("a,b,c".rsplit(",", 0))
print("  a  b  ".rsplit(None, 0))
