print("Hello World".istitle())
print("Hello world".istitle())
print("Hello-World".istitle())
print("Hello 123 World".istitle())
print("123".istitle())
print("".istitle())
print("A".istitle())
print("a".istitle())
print(["Title Case".istitle(), "Title case".istitle(), "1 A".istitle()])
