empty_a = range(0)
empty_b = range(2, 1, 3)
single_a = range(5, 6, 9)
single_b = range(5, 100, 200)
normal_a = range(1, 8, 2)
normal_b = range(1, 9, 2)

print(hash(empty_a) == hash(empty_b))
print(hash(single_a) == hash(single_b))
print(hash(normal_a) == hash(normal_b))
print(hash(empty_a) == hash((0, None, None)))
print(hash(single_a) == hash((1, 5, None)))
print(hash(normal_a) == hash((4, 1, 2)))
print(normal_a.__hash__() == hash(normal_a))
print(hash(range(0, 4, 2)) == hash(range(0, 5, 2)))
print(hash(range(0, 4, 2)) == hash(range(0, 6, 2)))
