print("".splitlines())
print("one line".splitlines())
print("one line\n".splitlines())
print("ab c\n\nde fg\rkl\r\n".splitlines())
kept = "ab c\n\nde fg\rkl\r\n".splitlines(True)
print(kept[0] == "ab c\n")
print(kept[1] == "\n")
print(kept[2] == "de fg\r")
print(kept[3] == "kl\r\n", len(kept[3]))
print("a\v b\f c\x1c d\x1d e\x1e f\x85 g\u2028 h\u2029".splitlines())
print("a\nb".splitlines(False))
print("a\nb".splitlines(True)[0] == "a\n")
