empty = ()
one = (1,)
items = (1, "x", None, True, (2, 3))
print(empty, one, items)
print(len(empty), len(one), len(items))
print(bool(empty), bool(one), bool(items))
print(items[0], items[-1], items[4][1])
print(1 in items, False in items, None in items, (2, 3) in items)
print((1, 2) == (1, 2), (1, 2) == (1, 3), (1, True) == (True, 1))
print((1, 2) + (3,), ("a",) * 3, 2 * (None,))
