import import_value

reader = import_value.__loader__.get_resource_reader(import_value.__name__)
handle = reader.open_resource("import_value.py")

first = handle.readline()
print(type(handle).__name__)
print(type(first).__name__)
print(len(first))
print(first[-1])
print(handle.tell())
second = handle.readline(2)
print(len(second))
print(handle.tell())
third = handle.readline(1000)
print(len(third) > 0)
print(third[-1])
print(handle.readline(0))
print(handle.tell())
handle.seek(0)
print(len(handle.readline(-1)) > 0)
print(handle.readline(None)[-1])
handle.close()
print(handle.closed)
