print("a\tb\tc".expandtabs())
print("a\tb\tc".expandtabs(4))
print("\tstart".expandtabs(4))
print("ab\tc".expandtabs(4))
print("ab\tc".expandtabs(0))
print("ab\tc".expandtabs(-2))
print("a\n\tb".expandtabs(4))
print("a\r\tb".expandtabs(4))
print("no tabs".expandtabs(4))
print(["x\ty".expandtabs(3), "x\t\ty".expandtabs(3), "".expandtabs()])
print("x\ty".expandtabs(True))
print("x\ty".expandtabs(False))
