text = "banana bandana"
print(text.find("a"))
print(text.find("ana"))
print(text.find("ana", 2))
print(text.find("ana", 4))
print(text.find(""))
print(text.find("", 3))
print(text.find("", 20))
print(text.find("a", -6))
print(text.find("a", 0, 5))
print(text.find("a", 0, -1))
print(text.find("na", -10, -1))
print(text.find("aa"))
print(text.find("banana bandana"))
print(text.find("a", None, None))
print("aaaa".find("aa", True, 4))
