import import_value

reader = import_value.__loader__.get_resource_reader(import_value.__name__)
handle = reader.open_resource("import_value.py")

peeked = handle.peek(5)
print(type(handle).__name__)
print(type(peeked).__name__)
print(len(peeked) > 0)
print(peeked[0])
print(handle.tell())
first = handle.read(5)
print(first[0] == peeked[0])
print(first[-1] == peeked[4])
print(handle.tell())
again = handle.peek(3)
print(len(again) > 0)
print(handle.tell())
second = handle.read(1)
print(second[0] == again[0])
print(handle.seek(0, 2) > 0)
print(handle.peek(5))
print(handle.tell() > 0)
handle.close()
print(handle.closed)
