text = "banana bandana"
print(text.startswith("ban"))
print(text.startswith("ana", 1))
print(text.startswith("ban", 1))
print(text.startswith("band", 7))
print(text.startswith("band", -7))
print(text.startswith("", 20))
print(text.startswith("", 14))
print(text.startswith("a", None, None))
print("aaaa".startswith("aa", True, 4))
print(text.endswith("ana"))
print(text.endswith("ban", 0, 3))
print(text.endswith("band", 0, -3))
print(text.endswith("band", 0, 11))
print(text.endswith("ana", -3))
print(text.endswith("", 20))
print(text.endswith("", 14))
print(text.endswith("a", None, None))
print("aaaa".endswith("aa", True, 4))
