text = "banana bandana"
print(text.count("a"))
print(text.count("ana"))
print(text.count(""))
print(text.count("a", 2))
print(text.count("a", -6))
print(text.count("a", 0, 5))
print(text.count("a", 0, -1))
print(text.count("na", -10, -1))
print(text.count("aa"))
print(text.count("banana bandana"))
print(text.count("a", None, None))
print("aaaa".count("aa"))
print("aaaa".count("aa", True, 4))
