import math
from math import acos, acosh, asin, asinh, atan, atan2, atanh, cbrt
from math import ceil, comb, copysign, cos, cosh, degrees, dist, erf, erfc
from math import exp, exp2, expm1, fabs, factorial, floor, fma, fmod, frexp, fsum
from math import gamma, gcd, hypot, isclose, isfinite, isinf, isnan, isqrt
from math import lcm, ldexp, lgamma, log, log1p, log10, log2, modf, nextafter
from math import perm, pow, prod, radians, remainder, sin, sinh, sqrt, sumprod
from math import tan, tanh, trunc, ulp

print(isnan(math.nan))
print(isinf(math.inf))
print(isfinite(math.pi))
print(isclose(acos(1), 0.0))
print(isclose(acosh(1), 0.0))
print(isclose(asin(0), 0.0))
print(isclose(asinh(0), 0.0))
print(isclose(atan(1), atan2(1, 1)))
print(isclose(atan2(1, 1), radians(45)))
print(isclose(atanh(0), 0.0))
print(isclose(cbrt(27), 3.0))
print(ceil(3.1))
print(comb(5, 2))
print(copysign(3, -1))
print(isclose(cos(0), 1.0))
print(isclose(cosh(0), 1.0))
print(isclose(degrees(math.pi), 180.0))
print(dist([1, 2, 3], [1, 6, 6]))
print(isclose(erf(0), 0.0))
print(isclose(erfc(0), 1.0))
print(isclose(exp(0), 1.0))
print(isclose(exp2(5), 32.0))
print(isclose(expm1(0), 0.0))
print(fabs(-4))
print(factorial(6))
print(floor(3.9))
print(fma(2, 3, 4))
print(fmod(7, 2))
print(frexp(8))
print(fsum([1.0, 2.0, 3.0]))
print(isclose(gamma(5), 24.0))
print(gcd(24, 36, 60))
print(hypot(3, 4, 12))
print(isqrt(17))
print(lcm(6, 10, 15))
print(ldexp(0.5, 4))
print(lgamma(5) > 3.0)
print(isclose(log(math.e), 1.0))
print(isclose(log(8, 2), 3.0))
print(isclose(log1p(0), 0.0))
print(isclose(log10(100), 2.0))
print(isclose(log2(8), 3.0))
print(modf(3.5))
print(nextafter(1.0, 2.0) > 1.0)
print(perm(5, 2))
print(perm(5))
print(pow(2, 3))
print(prod([2, 3, 4]))
print(isclose(radians(180), math.pi))
print(remainder(7, 2))
print(isclose(sin(math.pi / 2), 1.0))
print(isclose(sinh(0), 0.0))
print(sqrt(81))
print(sumprod([1, 2, 3], [4, 5, 6]))
print(isclose(tan(0), 0.0))
print(isclose(tanh(0), 0.0))
print(trunc(-3.9))
print(ulp(1.0) > 0.0)
