text = "banana bandana"
print(text.rfind("a"))
print(text.rfind("ana"))
print(text.rfind("ana", 0, 6))
print(text.rfind("ana", 2))
print(text.rfind("ana", 4))
print(text.rfind(""))
print(text.rfind("", 3))
print(text.rfind("", 20))
print(text.rfind("a", -6))
print(text.rfind("a", 0, 5))
print(text.rfind("a", 0, -1))
print(text.rfind("na", -10, -1))
print(text.rfind("aa"))
print(text.rfind("banana bandana"))
print(text.rfind("a", None, None))
print("aaaa".rfind("aa", True, 4))
