print("banana".replace("na", "NA"))
print("banana".replace("na", "NA", 1))
print("banana".replace("na", "NA", 0))
print("banana".replace("x", "X"))
print("aaaa".replace("aa", "b"))
print("aaaa".replace("aa", "b", 1))
print("abc".replace("", "-"))
print("abc".replace("", "-", 2))
print("abc".replace("", "-", 0))
print("abab".replace("ab", "X", True))
print("abab".replace("ab", "X", False))
