empty = ()
print(tuple() is empty)
print(tuple([]) is empty)
print(tuple(()) is empty)
print((1, 2)[1:1] is empty)
print((1, 2)[2:] is empty)
print(empty[:] is empty)
print(empty[::1] is empty)
print((1, 2)[::-3] is empty)
