items = (1, True, 0, False, None, "1", 1, (2, 3), (2, 3), (True, 1))
print(items.count(1))
print(items.count(True))
print(items.count(0))
print(items.count(False))
print(items.count(None))
print(items.count("1"))
print(items.count(3))
print(items.count((2, 3)))
print(items.count((1, True)))
print(().count(1))
