text = "banana bandana"
print(text.rindex("a"))
print(text.rindex("ana"))
print(text.rindex("ana", 0, 6))
print(text.rindex("ana", 2))
print(text.rindex("ana", 4))
print(text.rindex(""))
print(text.rindex("", 3))
print(text.rindex("", 14))
print(text.rindex("a", -6))
print(text.rindex("a", 0, 5))
print(text.rindex("a", 0, -1))
print(text.rindex("na", -10, -1))
print(text.rindex("banana bandana"))
print(text.rindex("a", None, None))
print("aaaa".rindex("aa", True, 4))
