import import_value

reader = import_value.__loader__.get_resource_reader(import_value.__name__)
handle = reader.open_resource("import_value.py")
lines = handle.readlines()
print(type(handle).__name__)
print(type(lines).__name__)
print(type(lines[0]).__name__)
print(len(lines) > 0)
print(lines[0])
print(handle.tell() > 0)
print(handle.readlines())
handle.seek(0)
print(handle.readline())
handle.seek(0)
hinted = handle.readlines(1)
print(len(hinted), len(hinted[0]), handle.tell())
handle.close()
print(handle.closed)
