print(__name__)
print(__package__)
print(__loader__.name == __name__)
print(__loader__ is __spec__.loader)
print(__spec__.name == __name__)
print(__spec__.parent)
print(__spec__._initializing)
print(__file__.endswith("test/import_metadata_globals.py"))
print(__cached__ == __spec__.cached)
